### ISSUE TITLE
trying to apply WHERE clause

### ISSUE THREAD

**Issue by mwallet** [ggarri/mysql2psql#1]
@ggarri could you elaborate on how to use a _WHERE_ clause in the rules?

**Comment by ggarri** [comment]
Hi @mwallet sorry for the late reply and I have been very busy at work for past weeks and I lost track on my personal stuff. 

WHERE rules are meant to filter the original source data from the table you are migrating from Mysql to Psql. My reason for that feature was to skip data which was not useful anymore on the Psql db such as very old log entries and so on. In case you want to add the you just include a list of string using mysql syntax, for example:
```
_WHERE: [
`created_at < 2017-01-01 AND updated_at is null`
]
```
Would you mind to elaborate more your question? Sorry if I am not being entirely accurate, feel to open a discussion here but I didn't work on this repo for a long while and I currently do not have access to the project I migrated to fetch some exact examples, but I will do it along next week.

Regarding your PR I will do my best to review within the following week.Thanks very much for your contribution

**Comment by mwallet** [comment]
Thanks @ggarri ! I already figured out the below:
`{
    "tables": {
       "transaction": {"_WHERE_": "id > 1520431"},
       "transaction_redeem_data": {"_WHERE_": "transaction > 1520431"}
            }
}`
but it would also be nice to know how to join two tables.
Maybe, there could be some examples added to the code, cause the above I had to find out myself.

**Comment by ggarri** [comment]
Unforturtunally the joining of two tables (_JOIN_) was not implemented yet. Instead, you could do as many _PRE_SQL_ queries are you require before table migration started as follow:
```
"reservation_reminder": {
            "_PRE_SQL_": [
                "DELETE IGNORE FROM reservation_reminder WHERE resa_id NOT IN (SELECT id FROM reservation)"
            ],
            "name": "reminder",
            "columns": {
                "resa_id": {
                    "name": "reservation_id",
                    "reference": "reservation (id)"
                },
                "user_id": {
                    "nullable": true
                },
                "client_id": {
                    "reference": "client (id)"
                }
            }
        },
```

At this example, you can also see how to instantiate FK(reference) on migration time. I hope that example is useful and sorry for the delay.

**Comment by mwallet** [comment]
No problem, thanks.
